#!/bin/bash

NAME=clusterware
SOURCE=$1

if [[ -z "${alces_PATH:-}" ]]; then
  if (( UID == 0 )); then
    alces_PATH="/opt/clusterware/"
  else
    alces_PATH="${HOME}/.alces"
  fi
fi

alces_SRC_PATH="$alces_PATH/var/cache/$NAME/src"
alces_ARCHIVES_PATH="$alces_PATH/var/cache/$NAME/archives"
export alces_PATH alces_SRC_PATH alces_ARCHIVES_PATH

for dir in "$alces_SRC_PATH" "$alces_ARCHIVES_PATH"; do
  if [[ ! -d "$dir" ]]; then
    mkdir -p "$dir"
  fi
done

# 0. Install dependencies
cat <<EOF
^[[33m
===============================================================================
 INSTALLING DEPENDENCIES
===============================================================================
^[[0m
EOF


yum -e0 -y  install ncurses-devel libevent-devel sqlite-devel libpcap-devel flex git

# 1. download tarball

cat <<EOF
[33m
===============================================================================
 DOWNLOADING SOURCE
===============================================================================
[0m
EOF

git clone https://github.com/alces-software/clusterware.git "${alces_ARCHIVES_PATH}/${NAME}"

if [ $? -gt 0 ]; then
  echo "Unable to clone source, aborting."
  exit 1
fi

cat <<EOF
[33m
===============================================================================
 BOOTSTRAPPING INSTALLER
===============================================================================
[0m
EOF

cd "${alces_ARCHIVES_PATH}/${NAME}"
chmod +x ./scripts/fetch_archives.sh
./scripts/fetch_archives.sh
chmod +x ./scripts/install
./scripts/install
