#!/bin/bash

NAME=clusterware

alces_yaml_version=0.1.4
alces_ruby_version=1.9.3-p484
alces_git_version=1.7.11.1
alces_tmux_version=1.6
alces_bundler_version=1.1.4

# ensure all children die when we do
trap "/bin/kill -- -$BASHPID &>/dev/null" EXIT INT TERM

function toggle_spin () {
	if [ -z "$spin_pid" ]; then
	    (
		i=1
		sp="/-\|"
		printf " "
		while true;
		do
		    printf "\b[1m${sp:i++%${#sp}:1}[0m"
		    if [[ i -eq ${#sp} ]]; then
			i=0
		    fi
		    sleep 0.2
		done
	    ) &
	    sleep 1
	    spin_pid=$!
	else
	    sleep 1
	    kill $spin_pid
	    wait $spin_pid 2>/dev/null
	    printf "\b"
	    unset spin_pid
	fi
}

function title() {
    printf "\n > $1\n"
}

function doing() {
    if [ -z "$2" ]; then
	pad=12
    else
	pad=$2
    fi
    printf "    [36m%${pad}s[0m ... " "$1"
    toggle_spin
}

function say_done () {
    toggle_spin
    if [ $1 -gt 0 ]; then
	echo '[31mFAIL[0m'
	exit 1
    else
	echo '[32mOK[0m '
    fi
}

cat <<EOF
[33m===============================================================================
 STARTING INSTALLATION
===============================================================================[0m
EOF

title "Creating initial directory structure"
doing 'Create'
[[ -d "${alces_PATH}/opt/${NAME}" ]] || mkdir -p "${alces_PATH}/opt/${NAME}"
cp -r "${alces_SRC_PATH}/${NAME}/bin" "${alces_SRC_PATH}/${NAME}/lib" "${alces_PATH}/opt/${NAME}"

# Make directories
LOGDIR="var/log/clusterware"
for a in bin etc $LOGDIR var/spool var/spool/tasks; do
    [[ -d "${alces_PATH}/${a}" ]] || mkdir -p "${alces_PATH}/${a}"
done
say_done $?

# Create initial configuration files
title "Creating initial configuration"
doing "Create"
if (( UID == 0 )); then
    cp -r "${alces_SRC_PATH}/${NAME}/etc/global"/* "${alces_PATH}/etc"
    cp -r "${alces_SRC_PATH}/${NAME}/etc/system"/* "${alces_PATH}/etc"
else
    cp -r "${alces_SRC_PATH}/${NAME}/etc/global"/* "${alces_PATH}/etc"
    cp -r "${alces_SRC_PATH}/${NAME}/etc/user"/* "${alces_PATH}/etc"
fi
say_done $?

#install deps tree
/bin/bash ${alces_SRC_PATH}/${NAME}/scripts/build $alces_BUILD_DEPS

title "Activating 'alces' command"
doing 'Create'

# Symlink binary
[[ -e "${alces_PATH}/bin/alces" ]] || ln -s "${alces_PATH}/opt/${NAME}/bin/${NAME}" "${alces_PATH}/bin/alces"

say_done $?

ppid=`ps -p ${1:-$$} -o ppid=`
user_shell=`lsof -p $ppid | awk '(NR==2) {print $1}'`

case $user_shell in
    sh|bash|ksh|zsh)
	rc_script_ext=sh
	;;
    tcsh|csh)
	rc_script_ext=csh
	;;
    *)
	rc_script_ext=sh
	;;
esac

# different branch for root (system-wide) install
if (( UID == 0 )); then
    if [ -d ${alces_PATH}/etc/profile.d ]; then
	# we've discovered an alces stack most likely!
	TARGET=${alces_PATH}/etc/profile.d
    else
	TARGET=/etc/profile.d
    fi
    mv "${alces_PATH}/etc/alces-clusterware.sh" $TARGET/alces-clusterware.sh
    mv "${alces_PATH}/etc/alces-clusterware.csh" $TARGET/alces-clusterware.csh
    cat <<EOF
[33m
===============================================================================
 INSTALLATION COMPLETE
===============================================================================
[0m[1m
Global profile scripts have been installed in:

$TARGET/alces-clusterware.sh
$TARGET/alces-clusterware.csh

Please login again, or manually run the following:

source $TARGET/alces-clusterware.${rc_script_ext}

Afterwards, execute 'alces' for further information.
[0m
EOF
else
    cat <<EOF
[33m
===============================================================================
 INSTALLATION COMPLETE
===============================================================================
[0m[1m
EOF
    if [ "$rc_script_ext" == 'sh' ]; then
    cat <<EOF
Please add the following to your shell startup file:

[[ -s "\$HOME/.alces/etc/clusterware.sh" ]] && . "\$HOME/.alces/etc/clusterware.sh"

Once added, please login again, or manually run the following:

source "\$HOME/.alces/etc/clusterware.sh"
EOF
    else
    cat <<EOF
Please add the following to your shell startup file:

if ( -f "\$HOME/.alces/etc/clusterware.csh" ) then
  source "\$HOME/.alces/etc/clusterware.csh"
endif

Once added, please login again, or manually run the following:

source "\$HOME/.alces/etc/clusterware.csh"
EOF
    fi
cat <<EOF

Afterwards, execute 'alces' for further information.
[0m
EOF
fi
